// Embeds the static dashboard (public/) into the Edge Function as supabase/functions/kiosk/assets.ts,
// so one deploy carries the dashboard and the API. Run before `supabase functions deploy kiosk`.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, extname } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const pub = join(root, "public");
const out = join(root, "supabase/functions/kiosk/assets.ts");
const types = {
  ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml", ".png": "image/png", ".ico": "image/x-icon", ".woff2": "font/woff2", ".json": "application/json",
  ".txt": "text/plain; charset=utf-8", ".ps1": "text/plain; charset=utf-8", ".sh": "text/plain; charset=utf-8", ".webmanifest": "application/manifest+json",
};
const files = {};
let total = 0;
(function walk(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) { walk(p); continue; }
    const ext = extname(name);
    if (!types[ext] || name.endsWith(".apk")) continue;
    const buf = readFileSync(p);
    total += buf.length;
    files["/" + relative(pub, p).split("\\").join("/")] = { type: types[ext], immutable: ext === ".woff2", b64: buf.toString("base64") };
  }
})(pub);
writeFileSync(out, `// Generated by scripts/build-assets.mjs — do not edit. ${Object.keys(files).length} files, ${(total / 1024).toFixed(0)} KB.\nexport const ASSETS: Record<string, { type: string; b64: string; immutable?: boolean }> = ${JSON.stringify(files)};\n`);
console.log(`wrote ${relative(root, out)}: ${Object.keys(files).length} files, ${(total / 1024).toFixed(0)} KB`);
